# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  deployToProduction: false

sum(irate(container_cpu_usage_seconds_total{kubernetes_container_name=~".+", kubernetes_namespace=~".+"}[20s])) by (kubernetes_namespace,kubernetes_container_name) + 
topk(5,avg_over_time(sum(irate(container_cpu_usage_seconds_total{kubernetes_container_name=~".+", kubernetes_namespace=~".+"}[20s])) 
by (kubernetes_namespace,kubernetes_container_name)[$__range:4h]))*0



stages:
- stage: 'BUILD_PUBLISH'
  jobs:
  - job: PUBLISH
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        publishWebProjects: true

- stage: 'DEPLOY_STAGING'
  dependsOn: BUILD_PUBLISH
  jobs:
  - job: DEPLOY_STAGING
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy to Staging'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        appName: $(appName)
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deployToSlotOrASE: true
        slotName: 'staging'

- stage: 'DEPLOY_PRODUCTION'
  dependsOn: BUILD_PUBLISH
  condition: eq(variables['deployToProduction'], 'true')
  jobs:
  - job: DEPLOY_PRODUCTION
    steps:
    - task: AzureWebApp@1
      displayName: 'Deploy to Production'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      inputs:
        azureSubscription: $(azureSubscription)
        appType: 'webAppLinux'
        appName: $(appName)
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        deployToSlotOrASE: true
        slotName: 'production'